# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srs', '0002_auto_20170212_1811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notefile',
            unique_together=set([('author', 'name')]),
        ),
    ]
