# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0007_auto_20170216_1637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notefile',
            unique_together=set([]),
        ),
    ]
